### ISSUE TITLE
Can't use meta::doForAllMembers for types with just one registered member

### ISSUE THREAD

**Issue by w1th0utnam3** [EliasD/MetaStuff#3]
Thanks for sharing this library, it's really useful. However I discovered that it is not possible to compile (using MSVC15) code that relies on `meta::doForAllMembers` when only one member is registered for a type. I think it would be sensible to not force the user to handle this as a special case. 

I'm not a meta programming expert but I tracked it down to the `apply` and `apply_impl` methods in [template_helpers.inl](https://github.com/EliasD/MetaStuff/blob/master/include/template_helpers.inl) where
```c++
std::make_index_sequence<std::tuple_size<std::decay_t<Tuple>>::value>{};
```
won't create a sequence for `std::tuple_size<std::decay_t<Tuple>>::value == 1`. I created a temporary fix by providing overloads for this case without the use of the sequence. I made a [pull request](https://github.com/EliasD/MetaStuff/pull/4) from my fix but maybe you want to handle this differently.

The following code generates the compiler error:
```c++
#include "Meta.h"

#include <iostream>

struct TestStruct
{
	int someValue;
	int someValue2;
};

namespace meta
{
	template <>
	inline auto registerMembers<TestStruct>()
	{
		return members(
			member("someValue", &TestStruct::someValue)
			// Works if following line is uncommented:
			// , member("someValue2", &TestStruct::someValue2)
		);
	}
}

void main(int, char**)
{
	TestStruct test{42, 4711};

	std::cout << "Values in TestStruct:\n";
	meta::doForAllMembers<TestStruct>(
		[&test](auto& member) {
			std::cout << "* " << member.getName() << ": " << member.get(test) << '\n';
		});
}
```
If you're interested, here's the compiler output: [cl_error.txt](https://github.com/EliasD/MetaStuff/files/344495/cl_error.txt)

**Comment by EliasD** [comment]
You're welcome :)

This was indeed the problem with VS, probably compiler problem: it couldn't deduce template arguments for index_sequence properly when make_index_sequence was used. 
Instead of going with std::enable_if, I've created function which returns std::index_sequence for specified number of args and does it without make_index_sequence for 1 member. 

(Btw, this problem was fixed with VS 2015 Update 3)

**Comment by w1th0utnam3** [comment]
Cool, thanks for the fix. At the moment I'm getting a linker error because `meta::detail::makeIndexSequence<1>(void)` is defined in multiple units. I don't have time to look into it right now but I'll check it out tonight. I tried to compile it with with VS15 Preview Update 2 and VS2015 Update 3.

**Comment by EliasD** [comment]
Oops! :D
[Fixed this by making the function inline](https://github.com/EliasD/MetaStuff/commit/046e592f23857c433b809e58700fcbf2f4ca696d)

**Comment by w1th0utnam3** [comment]
Thanks. Works as intended now. :)

**Comment by EliasD** [comment]
You're welcome :)
